# Generated by Django 3.0.6 on 2020-05-29 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Поиск',
            },
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('ide', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('duration', models.CharField(max_length=32)),
                ('thumbnail', models.CharField(max_length=512)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('ide', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('duration', models.CharField(max_length=32)),
                ('thumbnail', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
            },
        ),
    ]
